DP4-1 [Users] Access for different user roles
koleshkos/Project-Shop pull request #1
Opened 2022-01-21 09:02 UTC by koleshkos

I have two user roles: User and Admin. In order to differentiate access to the functionality, i created a separate URL for the Admin. 

Setup the following URLs for admin and user: 
URL for admin:
    [website_home_page]/admin - admin's homepage 
    [website_home_page]/admin/[page_name] - other pages
URL for user:
    [website_home_page]- user's hamepage 
    [website_home_page]/[page_name] - other pages

2022-01-25 07:15 UTC, DmitryGolubko requested changes
changes requested
TODO: 
1. Let's use the following git commits convention:
`Ticket number(DP4-1) - commit name`
2. Setup CircleCI for automatic tests and style checker running 
3. Setup Heroku app for automatic deploy when tests pass
Contact me or Danila if there are any questions

2022-01-25 07:15 UTC, DmitryGolubko commented on app/helpers/pages_helper.rb
> +end
remove empty helpers

2022-01-25 07:15 UTC, DmitryGolubko commented on app/views/admin/index.html.erb
> +<h1>Welcome ADMIN to app MY SHOP</h1>
let's use haml or slim as template engine, as it's more popular and compact

2022-01-25 07:15 UTC, DmitryGolubko commented on config/routes.rb
> +  resources :admin
are we going to do crud operations on admin resources? Let's make just an admin scope and `resource :products` for products crud

2022-01-25 07:15 UTC, DmitryGolubko commented on spec/controllers/admin_spec.rb
> +      expect(subject).to render_template('admin/index')
these expectations are the same, leave just one of them

2022-01-25 07:15 UTC, DmitryGolubko commented on spec/controllers/pages_spec.rb
> +      expect(subject).to render_template('pages/home')
the same

2022-01-27 09:03 UTC, DmitryGolubko requested changes
remove admin controller

2022-01-27 09:03 UTC, DmitryGolubko commented on app/controllers/admin_controller.rb
> +end
If you'll look at the following tasks, you'll see that you have to work with products resources, so you don't need admin controller here, as we don't have any admin model or smth like.

2022-01-27 09:09 UTC, koleshkos commented on app/controllers/admin_controller.rb
> +end
I got it. I solve this problem

2022-01-27 14:19 UTC, koleshkos commented
- Removed admin controller
- Added rubocop check to circleCI
- Setup CircleCi for test
- Used HAML
- Added specs

2022-01-28 07:24 UTC, DmitryGolubko approved these changes
Approvec

2022-01-28 14:01 UTC, koleshkos commented
Added Rubocop run in separate CircleCI job

2022-01-28 14:54 UTC, DmitryGolubko approved these changes
Approved

2022-01-28 14:57 UTC, merged