DP4-2 [Admin] Create/Update product
koleshkos/Project-Shop pull request #2
Opened 2022-02-01 10:05 UTC by koleshkos

- Added button "Create"/"Edit"
- Validates for Product model:
  - Name
  - Image
  - Code
  - Price
  - Description
- Added Bootstrap

2022-02-02 13:08 UTC, DmitryGolubko requested changes
Changes requested.

TODO: 
1. Remove all temp images from the github, github is not intended for storing images
2. Migrate image storing to AWS
3. Write specs for your model and controller, check that everything is working correct

2022-02-02 13:08 UTC, DmitryGolubko commented on app/views/layouts/application.html.erb
> +            <a class="navbar-brand" href="/">MℽSℍOℙ</a>
what a strange symbols in `MℽSℍOℙ`, use normal ones

2022-02-02 13:08 UTC, DmitryGolubko commented on app/views/layouts/application.html.erb
> +            <li><%= link_to 'Product', products_path, class: 'nav-link px-2 text-white'%></li>
Is it a link to a product list? then we should name it 'Products'

2022-02-02 13:08 UTC, DmitryGolubko commented on app/views/layouts/application.html.erb
> +            <%= link_to 'About', root_path, class: 'text-decoration-none text-white-50'%>
Are we gonna have these pages? remove if not

2022-02-02 13:08 UTC, DmitryGolubko commented on app/views/products/new.html.haml
> +    = f.submit 'Save', class: 'btn btn-primary'
What's the difference between `new` and `edit` partials? Let's create separate partial 'views/products/_form' for form only and render it for new and edit actions.

2022-02-02 13:08 UTC, DmitryGolubko commented on app/views/products/show.html.haml
> += @product.price
Let's use `number_to_currency` helper there for better price view
https://apidock.com/rails/ActionView/Helpers/NumberHelper/number_to_currency

2022-02-02 13:08 UTC, DmitryGolubko commented on db/migrate/20220131094309_create_products.rb
> +      t.integer :price
what if price will be with cents? let's use decimal here with `scale: 2`
https://nelsonfigueroa.dev/handling-decimal-precision-in-rails/

2022-02-02 13:08 UTC, DmitryGolubko commented on app/controllers/products_controller.rb
> +    @product = Product.find(params[:id])
let's move this finder to private method `get_product` which will be called for show, edit, update and destroy methods, use `before_filter` for this

2022-02-04 18:21 UTC, koleshkos commented
- Removed all temp images from the github
- Migrated image storing to AWS
- Added before_action :set_product
- Used  decimal  with scale: 2 for price
- Used number_to_currency helper  for better price view
- Added partials form for new and edit
- Changed link name to 'Products'
- Removed unnecessary links in footer
- Fixed name project in header

Next step:
 - Writing specs for  model and controller

2022-02-09 06:44 UTC, DmitryGolubko requested changes
couple of changes

2022-02-09 06:44 UTC, DmitryGolubko commented on spec/controllers/products_controller_spec.rb
> +  let(:product) { Product.create(name: 'Product', image: 'product.jpg', code: '12345RE', price: 1000, description: 'My Product') }
move product creation to factories, use factory_bot and faker gems.
Do the same for products with bad data using traits

2022-02-09 06:44 UTC, DmitryGolubko commented on spec/controllers/products_controller_spec.rb
> +      expect(response).not_to be_redirect
you also have to check that the new product is not created

2022-02-09 06:44 UTC, DmitryGolubko commented on spec/controllers/products_controller_spec.rb
> +      expect(response).to be_redirect
you also have to check that the new product is created

2022-02-09 06:44 UTC, DmitryGolubko commented on spec/controllers/products_controller_spec.rb
> +    end
the same as for creation

2022-02-09 06:44 UTC, DmitryGolubko commented on spec/models/product_spec.rb
> +  subject { Product.new(name: 'Product', image: 'product.jpg', code: '12345RE', price: 1000, description: 'My Product') }
the same move product creating to factories

2022-02-11 06:25 UTC, DmitryGolubko requested changes
check usage of id in new template and one more comment left about creating products

2022-02-11 06:25 UTC, DmitryGolubko commented on spec/controllers/products_controller_spec.rb
> +      get :new, params: { id: product }
Do we really need id in new template?

2022-02-11 12:07 UTC, DmitryGolubko approved these changes

2022-02-11 14:56 UTC, merged