DP4-5  [Admin] List of products
koleshkos/Project-Shop pull request #6
Opened 2022-03-12 14:12 UTC by koleshkos

Display
	 - Display status "deleted" for Admin 
	- Pagination

 Action
	- Select product
		- dispalay checkbox
		- select all
	- Delete product
		- display button delete 
		- popup

Restore product

2022-03-12 14:14 UTC, koleshkos commented
DONE:
 - Display "deleted" product for admin
 - Restore product
 - Pagination

2022-04-14 14:29 UTC, koleshkos commented
You can select multiple products and delete them:
![image](https://user-images.githubusercontent.com/23640391/163411874-363943af-3491-4931-b256-8aae5813b62a.png)

2022-04-25 11:38 UTC, koleshkos commented
If you hover over a product, displayed checkbox: 
![image](https://user-images.githubusercontent.com/23640391/165080577-61b181a3-dc80-49e6-943b-76b7d964cf27.png)

 if you selected checkbox, displayed all checkbox and button( selected all, reset all, deleted):
![image](https://user-images.githubusercontent.com/23640391/165081326-6e2da45c-3413-46b4-b222-0c644715afec.png)

if no selected checkbox, displayed displayed nothing:
![image](https://user-images.githubusercontent.com/23640391/165081652-ca319a7d-b3fc-4f22-af67-b49e15c4e75d.png)

2022-04-27 09:54 UTC, koleshkos commented
Request: /admin/products?page=5
If use wrong number page (<1) or (>max number page), you get correct number page

2022-05-05 08:44 UTC, DmitryGolubko requested changes
couple of comments. Make sure that CircleCI specs pass(use VPN while pushing commits as CircleCI blocks belarus accounts)

2022-05-05 08:44 UTC, DmitryGolubko commented on app/assets/stylesheets/application.scss
> +//}
remove if unused

2022-05-05 08:44 UTC, DmitryGolubko commented on app/controllers/products_controller.rb
> +  def page_limit
rename to max_page(products_count) and move to concerns https://www.bigbinary.com/learn-rubyonrails-book/keep-application-controller-clean.

2022-05-05 08:44 UTC, DmitryGolubko commented on app/controllers/products_controller.rb
> +  end
the same, move to concerns

2022-05-05 08:44 UTC, DmitryGolubko commented on app/javascript/packs/checkbox.js
> +$(document).ready(function(){
make all this functions arrow functions, and rename this module as seems that it used for product deleting

2022-05-05 08:44 UTC, DmitryGolubko commented on app/javascript/packs/card.js
> +$(document).ready(function(){
make all functions arrow functions and rename this module to understand what does it stands for

2022-05-05 08:44 UTC, DmitryGolubko commented on config/routes.rb
> +  get '/admin/products/:id/restore', to: 'products#restore', as: 'product_restore'
Are you sure that it's good to use `get` method there as we change the product in database?

2022-05-05 08:44 UTC, DmitryGolubko commented on config/routes.rb
> +  delete '/admin/products', to: 'products#destroy', as: 'delete_product'
why do you not place this admin routes inside `admin` scope?

2022-05-05 08:44 UTC, DmitryGolubko commented on spec/controllers/products_controller_spec.rb
> +      end
you can use create_list instead of this iterator https://www.rubydoc.info/gems/factory_bot/FactoryBot%2FSyntax%2FMethods:create_list

2022-05-05 08:44 UTC, DmitryGolubko commented on spec/requests/static_pages_spec.rb
> +    it 'body must match' do
make this block name more clear to understand. for example it 'returns first page if -1 is requested'

2022-05-05 08:44 UTC, DmitryGolubko commented on spec/requests/static_pages_spec.rb
> +      expect(response.body).to eq(res)
the same

2022-05-06 06:52 UTC, DmitryGolubko requested changes
2 changes

2022-05-06 06:52 UTC, DmitryGolubko commented on app/controllers/concerns/pagination.rb
> +    elsif page > max_page(Product.count)
if you will provide product count from the controller, you will make this methods more generic and reusable for other entities, and will remove 2 queries to DB from concerns

2022-05-06 06:52 UTC, DmitryGolubko commented on spec/requests/static_pages_spec.rb
> +    it 'returns last page if more tah max is requested' do
fix typo

2022-05-06 08:56 UTC, DmitryGolubko approved these changes

2022-05-06 09:03 UTC, merged